_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 55
                - 86
                - 92
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 75
                - 86
                - 92
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.11
            "5": 0.19.4
            "8":
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
reset_db:
    value: false
